### ISSUE TITLE
[WSL2] osc vc not detecting mktemp in openSUSE Leap 15.2 WSL2 environment

### ISSUE THREAD

**Issue by mark-stopka** [openSUSE/osc#857] opened 2020-10-20 11:57 UTC
Hi,
I am trying to use `osc vc` from openSUSE Leap 15.2 WSL2 environment, when I attempt to use it, I get the following errors...\

```
mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude> osc vc
mktemp is required for this script to work
mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude> mktemp
/tmp/tmp.2KnDJtm55G
mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude>
```

**OSC** version:
```
mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude> osc --version
0.170.0
```

**Comment by marcus-h** [comment] 2020-10-20 17:49
On 2020-10-20 04:58:15 -0700, Mark Stopka wrote:
> I am trying to use `osc vs` from openSUSE Leap 15.2 WSL2 environment, when I attempt to use it, I get the following errors...\
>
> ```
> mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude> osc vc
> mktemp is required for this script to work

That's an error message from the vc script (which is part of obs-build).
Do you have "which" installed? The vc script checks the retval of
"which mktemp...".

> mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude> mktemp
> /tmp/tmp.2KnDJtm55G
> mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude>

**Comment by mark-stopka** [comment] 2020-10-21 07:46
Hi, thanks for a quick reply, I do have `which` installed...

```
mark_stopka@NB20100:~> which mktemp
/usr/bin/mktemp
mark_stopka@NB20100:~>  
```

I do however don't have `obs-build` installed, nor is it available in my repositories... 

```
mark_stopka@NB20100:~> rpm -ql obs-build
package obs-build is not installed
mark_stopka@NB20100:~> sudo zypper install obs-build
Loading repository data...
Reading installed packages...
'obs-build' not found in package names. Trying capabilities.
No provider of 'obs-build' found.
Resolving package dependencies...
````

I was required to install only `build` to get the local builds running, I have inspected the `build` package and found:

```
mark_stopka@NB20100:~> rpm -ql build | grep vc
/usr/bin/buildvc
/usr/lib/build/vc
/usr/share/man/man1/buildvc.1.gz
mark_stopka@NB20100:~>
```

When I execute said scripts using `bash -x`, I get only the following output...

```
mark_stopka@NB20100:~> ll /usr/bin/ | grep vc
lrwxrwxrwx 1 root root         15 Aug 28 16:38 buildvc -> ../lib/build/vc
mark_stopka@NB20100:~> bash -x /usr/lib/build/vc
+ shopt -s nullglob
+ '[' -z '' ']'
++ dnsdomainname
+ domain=parfums.local
+ '[' -z parfums.local ']'
+ mailaddr=mark_stopka@parfums.local
+ '[' -n '' ']'
+ '[' -x /usr/bin/rpmdev-packager ']'
++ getent passwd 1000
++ cut -d: -f5
++ cut -d , -f 1
+ packager='Mark Stopka <mark_stopka@parfums.local>'
+ EDITOR=vim
++ LC_ALL=POSIX
++ TZ=UTC
++ date
+ date='Wed Oct 21 07:45:26 UTC 2020'
+ which mktemp
+ echo 'mktemp is required for this script to work'
mktemp is required for this script to work
+ exit 1
mark_stopka@NB20100:~>
````

**Comment by marcus-h** [comment] 2020-10-21 18:14
On 2020-10-21 00:46:33 -0700, Mark Stopka wrote:
> mark_stopka@NB20100:~> bash -x /usr/lib/build/vc

<SNIP>

> + which mktemp
> + echo 'mktemp is required for this script to work'
> mktemp is required for this script to work
> + exit 1

Hmm this looks interesting. What's the output if you run the
following bash script?

#!/bin/bash
which mktemp
echo $?
which mktemp > /dev/null 2>&1
echo $?
if ! which mktemp > /dev/null 2>&1 ; then
    echo "not found"
fi

**Comment by mark-stopka** [comment] 2020-10-21 18:37
> On 2020-10-21 00:46:33 -0700, Mark Stopka wrote: mark_stopka@NB20100:~> bash -x /usr/lib/build/vc
> <SNIP>
> + which mktemp + echo 'mktemp is required for this script to work' mktemp is required for this script to work + exit 1
> Hmm this looks interesting. What's the output if you run the following bash script? #!/bin/bash which mktemp echo $? which mktemp > /dev/null 2>&1 echo $? if ! which mktemp > /dev/null 2>&1 ; then echo "not found" fi

It's super funny, I don't know how it was happening, but apparently some magic version of `which` is present it Leap 15.2 WSL2 environment...

```
mark_stopka@NB20100:~> ./test.sh
./test.sh: line 2: which: command not found
127
127
not found
mark_stopka@NB20100:~> which osc
/usr/bin/osc
mark_stopka@NB20100:~> which which
mark_stopka@NB20100:~>
mark_stopka@NB20100:~> rpm -ql binutils | grep which
mark_stopka@NB20100:~>
mark_stopka@NB20100:~> sudo zypper install which
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  which

1 new package to install.
Overall download size: 38.8 KiB. Already cached: 0 B. After the operation, additional 75.1 KiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package which-2.21-lp152.4.114.x86_64                                   (1/1),  38.8 KiB ( 75.1 KiB unpacked)Retrieving: which-2.21-lp152.4.114.x86_64.rpm ....................................................................[done]
Checking for file conflicts: .....................................................................................[done]
(1/1) Installing: which-2.21-lp152.4.114.x86_64 ..................................................................[done]
mark_stopka@NB20100:~> which which
/usr/bin/which
mark_stopka@NB20100:~> cd Work/build.opensuse.org/devel\:languages\:haskell\:cardano/ghc-cardano-prelude/
mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude> osc vc
no changes made
mark_stopka@NB20100:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-prelude>
```

So perhaps add check for `which` into the script? Or even better make `which` a dependency of `osc` RPM package?

**Comment by mark-stopka** [comment] 2020-10-21 18:39
@mimi1vx still jealous about WSL2? 😂

**Comment by marcus-h** [comment] 2020-10-21 18:54
On 2020-10-21 11:37:29 -0700, Mark Stopka wrote:
> > On 2020-10-21 00:46:33 -0700, Mark Stopka wrote: mark_stopka@NB20100:~> bash -x /usr/lib/build/vc
> > <SNIP>
> > + which mktemp + echo 'mktemp is required for this script to work' mktemp is required for this script to work + exit 1
> > Hmm this looks interesting. What's the output if you run the following bash script? #!/bin/bash which mktemp echo $? which mktemp > /dev/null 2>&1 echo $? if ! which mktemp > /dev/null 2>&1 ; then echo "not found" fi
>
> It's super funny, I don't know how it was happening, but apparently some magic version of `which` is present it Leap 15.2 WSL2 environment...
>
Maybe some builtin or alias of your shell? If your shell is bash, you
could run "type -t which" (but I guess you are not using bash).

**Comment by mark-stopka** [comment] 2020-10-21 21:13
> On 2020-10-21 11:37:29 -0700, Mark Stopka wrote: > On 2020-10-21 00:46:33 -0700, Mark Stopka wrote: mark_stopka@NB20100:~> bash -x /usr/lib/build/vc > <SNIP> > + which mktemp + echo 'mktemp is required for this script to work' mktemp is required for this script to work + exit 1 > Hmm this looks interesting. What's the output if you run the following bash script? #!/bin/bash which mktemp echo $? which mktemp > /dev/null 2>&1 echo $? if ! which mktemp > /dev/null 2>&1 ; then echo "not found" fi It's super funny, I don't know how it was happening, but apparently some magic version of `which` is present it Leap 15.2 WSL2 environment...
> Maybe some builtin or alias of your shell? If your shell is bash, you could run "type -t which" (but I guess you are not using bash).

Must really be some WSL weirdness... This is openSUSE Leap 15.2 installed in WSL2 on my other laptop 2 months ago... Sufferef from the same issues though, I'll execute the same on my other machine (the `NB20100`) when I am in the office...

```
mark_stopka@mark-asus-zenbook-s:~> echo $SHELL
/bin/bash
```

**Comment by mark-stopka** [comment] 2020-10-23 04:14
> Maybe some builtin or alias of your shell? If your shell is bash, you could run "type -t which" (but I guess you are not using bash).

```
mark_stopka@mark-asus-zenbook-s:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-binary> type -t which
alias
mark_stopka@mark-asus-zenbook-s:~/Work/build.opensuse.org/devel:languages:haskell:cardano/ghc-cardano-binary> echo $SHELL
/bin/bash
```

**Comment by okurz** [comment] 2021-03-02 08:27
The issue reproduced for me and installing the package `which` rather than relying on the shell builtin makes `osc vc` work fine

**Comment by dmach** [comment] 2023-05-02 08:26
There doesn't seem to be any fix in osc necessary because installing package `which` fixes the problem.
Closing.

**Closed by dmach** 2023-05-02 08:26 UTC
