### ISSUE TITLE
biarchlib error on checkin: unknown option 3

### ISSUE THREAD

**Issue by afaerber** [openSUSE/osc#199] opened 2016-05-13 14:40 UTC
Since upgrading osc to openSUSE:Tools on Leap 42.1 x86_64 I get the following during `osc ci` after rpmlintrc checks and before sending the changed files:

```
biarchlib: Ungültige Option -- 3
error: Unknown option 3 in biarchlib()
biarchlib: Ungültige Option -- 3
error: Unknown option 3 in biarchlib()
biarchlib: Ungültige Option -- 3
error: Unknown option 3 in biarchlib()

```

The checkin does succeed afterwards, i.e. the error is non-fatal but would be nice to suppress one way or another.

**Comment by marcus-h** [comment] 2016-05-14 11:01
On 2016-05-13 07:40:52 -0700, Andreas Färber wrote:
> Since upgrading osc to openSUSE:Tools on Leap 42.1 I get the following during `osc ci` after rpmlintrc checks and before sending the changed files:
> 
> ```
> biarchlib: Ungültige Option -- 3
> error: Unknown option 3 in biarchlib()
> biarchlib: Ungültige Option -- 3
> error: Unknown option 3 in biarchlib()
> biarchlib: Ungültige Option -- 3
> error: Unknown option 3 in biarchlib()
> 
> ```
> 
Hmm I think these messages are caused by some _service that is
executed before sending the files (hence, probably not related to the
osc update itself). Did you also update an obs-service-* package?

> The checkin does succeed afterwards, i.e. the error is non-fatal but would be nice to suppress one way or another.
> 
Well... the question is whether this should be an error or not:)

**Comment by afaerber** [comment] 2016-05-14 12:44
Also obs-service-tar_scm and build, as indicated on http://openbuildservice.org/2016/04/08/new_git_in_27/

**Comment by dmach** [comment] 2021-12-28 08:10
I'm not sure if the issue is still reproducible after nearly 5 years.
Closing, but if it still persists, please create a new issue with a recent reproducer.

**Closed by dmach** 2021-12-28 08:10 UTC
