### ISSUE TITLE
AppImage crashes on Rocky Linux 8

### ISSUE THREAD

**Issue by rafaelorafaelo** [openSUSE/osc#1084] opened 2022-07-27 22:40 UTC
**Describe the bug**
I try to checkout a project. osc crashes with a Python error.

**Versions**
- Operating system: `(source /etc/os-release; echo $PRETTY_NAME)`
Rocky Linux 8.6 (Green Obsidian)
- Packages: `rpm -q osc`
N/A

**To Reproduce**
Download AppImage from https://download.opensuse.org/repositories/openSUSE:/Tools/AppImage/  osc-0.180.0-lp152.331.1.Build331.1.glibc2.26-x86_64.AppImage
Checkout a project: osc checkout Apache

**Expected behavior**
Project will be checked out.

**Screenshots, console outputs**
```
[geeko@localhost osb]$ osc checkout Apache
Traceback (most recent call last):
  File "/tmp/.mount_oscuCDbXh/usr/bin//osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/tmp/.mount_oscuCDbXh/usr/lib/python3.6/site-packages/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/tmp/.mount_oscuCDbXh/usr/lib/python3.6/site-packages/osc/cmdln.py", line 349, in main
    return self.cmd(args)
  File "/tmp/.mount_oscuCDbXh/usr/lib/python3.6/site-packages/osc/cmdln.py", line 372, in cmd
    retval = self.onecmd(argv)
  File "/tmp/.mount_oscuCDbXh/usr/lib/python3.6/site-packages/osc/cmdln.py", line 506, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/tmp/.mount_oscuCDbXh/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1237, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/tmp/.mount_oscuCDbXh/usr/lib/python3.6/site-packages/osc/commandline.py", line 4720, in do_checkout
    Project.init_project(apiurl, prj_dir, project, conf.config['do_package_tracking'], scm_url=scm_url)
  File "/tmp/.mount_oscuCDbXh/usr/lib/python3.6/site-packages/osc/core.py", line 1153, in init_project
    os.makedirs(dir)
  File "/tmp/.mount_oscuCDbXh/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: 'Apache'
```

**Additional context**
The checkout works, when I use the RHEL 8 version of osc from http://download.opensuse.org/repositories/openSUSE:/Tools/RHEL_8/

**Comment by dmach** [comment] 2023-05-23 07:15
Since #1075 is fixed now, I can reproduce this one. I'll take a look.

**Closed** 2023-05-23 14:00 UTC
Labels: Bug
