### ISSUE TITLE
osc does not find docker images in cache

### ISSUE THREAD

**Issue by jimmykarily** [openSUSE/osc#312] opened 2017-08-01 14:49 UTC
I'm using osc to build a fissile package (the latest supported format). My package is this:

https://build.opensuse.org/package/show/Cloud:Platform:scf:fissile-releases/uaa

Every time I run `osc build` (actually I use the osc-wrapper since I need the latest changes), the docker image specified [in the fissile.yml specification file](https://build.opensuse.org/package/view_file/Cloud:Platform:scf:fissile-releases/uaa/fissile.yml?expand=1) gets downloaded. It gets stored in the cache directory as `/var/tmp/osbuild-packagecache/Cloud:Platform:scf:images/images/noarch/container:docker.tar` but for some reason the next call to `osc build` doesn't recognize that file and it downloads it again. With this file being 1.3Gb, this is a big problem.

Maybe the problem is that the name of the file doesn't match the name of the dependency? I can't figure out where this filename is picked up.

**Comment by jimmykarily** [comment] 2017-08-02 07:24
Turns out that the [filename checked in fetch.py](https://github.com/openSUSE/osc/blob/master/osc/fetch.py#L268) is `/var/tmp/osbuild-packagecache/Cloud:Platform:scf:images/images/noarch/container:docker.tar.xz` while the actual file in the filesystem is the one above (without the `.xz`) extension. Maybe [this line is the problem](https://github.com/openSUSE/osc/blob/master/osc/fetch.py#L133)?

**Comment by mlschroe** [comment] 2017-08-02 08:31
The cache only works with .tar.xz, see https://github.com/openSUSE/osc/blob/master/osc/build.py#L234. The problem is that osc cannot know the correct extension from looking at the buildinfo.

We could add code that tries .tar.xz, .tar.gz and .tar when checking the cache, though.

**Comment by jimmykarily** [comment] 2017-08-02 08:40
Yes that should work.

**Comment by mlschroe** [comment] 2017-08-02 08:52
testing...

**Comment by mlschroe** [comment] 2017-08-02 09:02
Ok, fixed with commit c3e0bbccb2c18a3552fe83540690e9d553779ec8

**Closed by mlschroe** 2017-08-02 09:02 UTC
