### ISSUE TITLE
osc commit fails on SLE12-SP5 on AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by marcosps** [openSUSE/osc#1308] opened 2023-04-27 12:53 UTC
**Describe the bug**
osc -A https://api.suse.de/ commit -m update
Traceback (most recent call last):
  File "/usr/bin/osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 349, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 372, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 506, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1237, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4957, in do_commit
    self._commit(subcmd, opts, args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4992, in _commit
    for arg in args.copy():
AttributeError: 'list' object has no attribute 'copy'

**Versions**
- Operating system: SLE12-SP5
- Packages: `rpm -q osc`

**To Reproduce**
1. osc -A https://api.suse.de/ commit -m update
2. See error

**Expected behavior**
osc commit working

**Screenshots, console outputs**
If applicable, add screenshots or console outputs to help explain your problem.

**Additional context**
This bug happens on updates osc package on SLE12-SP5, as it still used python2.7

**Comment by dmach** [comment] 2023-04-27 13:35
Duplicate of #1266

**Closed by dmach** 2023-04-27 13:35 UTC
Labels: Bug
