### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#595] opened 2019-07-10 08:37 UTC
Interrupting osc build creates a lot of errors:

^CTraceback (most recent call last):
  File "/usr/lib64/python3.7/subprocess.py", line 325, in call
    return p.wait(timeout=timeout)
  File "/usr/lib64/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib64/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 6347, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.7/site-packages/osc/build.py", line 1246, in main
    rc = run_external(cmd[0], *cmd[1:])
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 7690, in run_external
    return subprocess.call(cmd, **kwargs)
  File "/usr/lib64/python3.7/subprocess.py", line 327, in call
    p.kill()
  File "/usr/lib64/python3.7/subprocess.py", line 1756, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib64/python3.7/subprocess.py", line 1746, in send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted

**Comment by dmach** [comment] 2022-12-16 07:24
I'm unable to reproduce the issue, there's a chance that it got fixed in unrelated changes during the last 3 years.

**Closed by dmach** 2022-12-16 07:24 UTC
Labels: python3
