### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by pgajdos** [openSUSE/osc#540] opened 2019-04-29 12:01 UTC
```
$ osc --version
0.165.0
$
```

I wanted to commit php5 for SLE 11 and SLE 10sp3 and I get:

```
$ isc ci
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 4700, in do_commit
    self._commit(subcmd, opts, args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 4792, in _commit
    msg = get_commit_msg(prj.absdir, pac_objs[prj_path])
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 7270, in get_commit_msg
    footer.extend([''.join(i) for i in p.get_diff(ignoreUnversioned=True)])
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 7270, in <listcomp>
    footer.extend([''.join(i) for i in p.get_diff(ignoreUnversioned=True)])
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 2056, in get_diff
    yield get_source_file_diff(self.absdir, f.name, self.rev)
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 4768, in get_source_file_diff
    s1 = f1.readlines()
  File "/usr/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 2264: invalid start byte
$

$ file php5.spec
php5.spec: ASCII text, with very long lines
$
```

With -m 'blabla' it seems to work.

**Comment by andreas-schwab** [comment] 2019-05-08 09:00
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4951, in do_update
    p.update(rev, opts.server_side_source_service_files, opts.limit_size)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 2330, in update
    self.__update(kept, added, deleted, services, ET.tostring(root, encoding=ET_ENCODING), root.get('rev'))
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 2419, in __update
    self.update_local_pacmeta()
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 1866, in update_local_pacmeta
    store_write_string(self.absdir, '_meta', meta + b'\n')
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 6483, in store_write_string
    f.write(string)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 152-153: ordinal not in range(128)

**Comment by andreas-schwab** [comment] 2019-05-08 09:04
$ osc api source/openSUSE:Factory/opencv/_meta\?meta=1
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/util/safewriter.py", line 15, in write
    self._writer.write(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 146-147: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 7979, in do_api
    sys.stdout.write(out)
  File "/usr/lib/python3.6/site-packages/osc/util/safewriter.py", line 17, in write
    self._writer.write(s.encode(self._encoding))
TypeError: write() argument must be str, not bytes

**Comment by lethliel** [comment] 2019-05-08 10:06
> 
> I wanted to commit php5 for SLE 11 and SLE 10sp3 and I get:
> 

[snip]

> 
> $ file php5.spec
> php5.spec: ASCII text, with very long lines
> $
> ```
> 
> With -m 'blabla' it seems to work.

Can you please provide the project and package? Thanks in Advance and also thanks for the issue report.

**Comment by lethliel** [comment] 2019-05-14 12:26
@andreas-schwab  

> $ osc diff
> Traceback (most recent call last):
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8067: ordinal not in range(128)

Is this also on 13.2? If not can you please tell me the project/package you are trying to do the diff?

**Comment by lethliel** [comment] 2019-05-14 13:17
> Use any and add something non-ascii.

I cannot reproduce this on current Versions of (open)SUSE. (Leap 15.0 / Tumbleweed). 
I just added the char U+2021	(double dagger ‡) to a spec file and osc diff worked without problems. 

Have you some special terminal settings?

**Comment by pgajdos** [comment] 2019-05-14 13:34
I can still reproduce with branching SLE-11/php5, add a space to whatever file and run `osc diff` or `osc ci`.

**Comment by lethliel** [comment] 2019-05-14 13:49
> I can still reproduce with branching SLE-11/php5, add a space to whatever file and run `osc diff` or `osc ci`.

I just did: 

1. osc branch SUSE:SLE-11:GA php5
2. osc co home:mstrigl:branches:SUSE:SLE-11:Update/php5
3. added a space and a double dagger (‡) to the spec file
4. osc diff works without problems

I am on openSUSE Leap 15.0 and on Tumbleweed.

**Comment by lethliel** [comment] 2019-05-14 13:52
@pgajdos @andreas-schwab Can you both please post the output of 

`env | grep LC`

**Comment by pgajdos** [comment] 2019-05-14 14:18
>     1. osc branch SUSE:SLE-11:GA php5
> 
>     2. osc co home:mstrigl:branches:SUSE:SLE-11:Update/php5
> 
>     3. added a space and a double dagger (‡) to the spec file
> 
>     4. osc diff works without problems

Hmm, I can not reproduce this way as well. But:
```
$ isc co home:pgajdos:maintenance:php5/php5.SUSE_SLE-11_Update
$ cd home:pgajdos:maintenance:php5/php5.SUSE_SLE-11_Update
$ echo ' ' >> php5.changes
$ osc diff
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 3862, in do_diff
    for i in pac.get_diff(rev1):
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 2056, in get_diff
    yield get_source_file_diff(self.absdir, f.name, self.rev)
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 4768, in get_source_file_diff
    s1 = f1.readlines()
  File "/usr/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 2748: invalid start byte
$
```
Perhaps this is an old branch. Unfortunately I can not recreate it to experiment more as there is a pending submit request from there to address a security update.

**Comment by lethliel** [comment] 2019-05-14 14:32
Ok. Found the problem. php5.changes already contains non-UTF8 or non-ASCII Characters. 

`grep -axv '.*' php5.changes` will show this. 

I have to find a way to get around this somehow.

**Comment by marcus-h** [comment] 2019-05-14 20:11
On 2019-05-14 07:32:43 -0700, Marco Strigl wrote:
> Ok. Found the problem. php5.changes already contains non-UTF8 or non-ASCII Characters.
>
> `grep -axv '.*' php5.changes` will show this.
>
> I have to find a way to get around this somehow.
>
Hmm what about opening the file with mode 'rb' and then use
difflib.diff_bytes(difflib.unified_diff, ...)?

**Comment by lethliel** [comment] 2019-05-15 06:18
On 5/14/19 10:11 PM, Marcus Hüwe  wrote:
> On 2019-05-14 07:32:43 -0700, Marco Strigl wrote:
>> Ok. Found the problem. php5.changes already contains non-UTF8 or
> non-ASCII Characters.
>>
>> `grep -axv '.*' php5.changes` will show this.
>>
>> I have to find a way to get around this somehow.
>>
> Hmm what about opening the file with mode 'rb' and then use
> difflib.diff_bytes(difflib.unified_diff, ...)?
> 

Yes. I played around with that option last night. I will open the file
in binary mode. That would be the best solution I think.

**Comment by lethliel** [comment] 2019-07-24 13:08
fixed with https://github.com/openSUSE/osc/commit/2b47be6b1e1eeb17957aba1f45c1af4433b6bdec

**Closed by lethliel** 2019-07-24 13:08 UTC
Labels: python3
