### ISSUE TITLE
Unsupported format character B

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#997] opened 2022-01-27 17:29 UTC
osc-0.175.0-1.2.noarch on tumbleweed 20220124

```
$ osc co devel:libraries:c_c++/libHX; cd there;
$ osc build --do --nopre openSUSE_Factory x86_64 2>&1|tee 
...
Getting buildconfig from server and store to /tmp/c_c++/libHX/.osc/_buildconfig-openSUSE_Factory-x86_64
Getting buildinfo from server and store to /tmp/c_c++/libHX/.osc/_buildinfo-openSUSE_Factory-x86_64.xml
GET https://api.opensuse.org/build/devel:libraries:c_c++/openSUSE_Factory/_buildconfig
Getting buildconfig from server and store to /home/jengelh/obs/zu/devel/libraries/c_c++/libHX/.osc/_buildconfig-openSUSE_Factory-x86_64
POST https://api.opensuse.org/build/devel:libraries:c_c++/openSUSE_Factory/x86_64/libHX/_buildinfo?add=gdb&add=vim&add=strace&add=less&add=rzsz

Updating cache of required packages
Traceback (most recent call last):
  File "/usr/bin/osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 6730, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.8/site-packages/osc/build.py", line 1074, in main
    fetcher.run(bi)
  File "/usr/lib/python3.8/site-packages/osc/fetch.py", line 210, in run
    i.makeurls(self.cachedir, urllist)
  File "/usr/lib/python3.8/site-packages/osc/build.py", line 291, in makeurls
    self.urllist.append(url % self.mp)
ValueError: unsupported format character 'B' (0x42) at index 66
```

**Comment by jengelh** [comment] 2022-01-27 17:32
```
$ osc api '/build/devel:libraries:c_c++/openSUSE_Factory/x86_64/libHX/_buildinfo?add=gdb&add=vim&add=strace&add=less&add=rzsz'|grep B
  <path project="devel:libraries:c_c++" repository="openSUSE_Factory" url="https://download.opensuse.org/repositories/devel:/libraries:/c_c%2B%2B/openSUSE_Factory/"/>
```
perhaps that's the particular B it trips over?

**Comment by marcus-h** [comment] 2022-01-27 19:26
On 2022-01-27 09:30:18 -0800, Jan Engelhardt wrote:
> $ osc co devel:libraries:c_c++/libHX; cd there;
> $ osc build --do --nopre openSUSE_Factory x86_64 2>&1|tee

<SNIP>

>   File "/usr/lib/python3.8/site-packages/osc/build.py", line 291, in makeurls
>     self.urllist.append(url % self.mp)
> ValueError: unsupported format character 'B' (0x42) at index 66
> ```
Already fixed in commit d549f27ec5a4e871ae7ba6f611cb49e9a17149e4 ("Escape
% character in binary download URLs").

**Comment by mcepl** [comment] 2022-02-04 11:05
Duplicate of https://github.com/openSUSE/osc/issues/965

**Comment by dmach** [comment] 2022-02-21 13:23
Closing as it's fixed already (see comments above).

**Comment by mcepl** [comment] 2022-02-21 14:35
No, it isn’t:
```
stitny~/b/t/d/libHX (1M)$ osc build --do --nopre openSUSE_Factory x86_64
Building libHX.spec for openSUSE_Factory/x86_64
Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/matej/build/tmp/devel:libraries:c_c++/libHX/tmpwx4o_el1.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /home/matej/build/tmp/devel:libraries:c_c++/libHX/tmpstn0yte2.source_validator.service
gpg: Podpis vytvořen Ne 17. října 2021, 18:54:51 CEST
gpg:                použití RSA klíče 23686C10A45691BE7A425109D6388181F35A0938
gpg: Dobrý podpis od „Jan Engelhardt <jengelh@inai.de>“ [neznámý formát]
- package has baselibs.conf: (unchanged)
Getting buildconfig from server and store to /home/matej/build/tmp/devel:libraries:c_c++/libHX/.osc/_buildconfig-openSUSE_Factory-x86_64
Getting buildinfo from server and store to /home/matej/build/tmp/devel:libraries:c_c++/libHX/.osc/_buildinfo-openSUSE_Factory-x86_64.xml
Updating cache of required packages
Traceback (most recent call last):
  File "/home/matej/.bin/osc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/matej/archiv/knihovna/repos/osc/osc-wrapper.py", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 6767, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.8/site-packages/osc/build.py", line 1074, in main
    fetcher.run(bi)
  File "/usr/lib/python3.8/site-packages/osc/fetch.py", line 210, in run
    i.makeurls(self.cachedir, urllist)
  File "/usr/lib/python3.8/site-packages/osc/build.py", line 291, in makeurls
    self.urllist.append(url % self.mp)
ValueError: unsupported format character 'B' (0x42) at index 66
stitny~/b/t/d/libHX (1M)$
```

With https://github.com/mcepl/osc/tree/12034-download-api-only.patch @ https://github.com/mcepl/osc/commit/57752191cd92acfee11a7be6577255ccc45da92d (i.e., this branch rebased on top of the current master https://github.com/openSUSE/osc/commit/fe6a50ffb76916c468d5e3cf66d8a5c63cbdc79a).

**Comment by dmach** [comment] 2022-02-28 08:56
The error above was caused because python modules from `/usr/lib/python3.8/site-packages/` were used. Closing again.

**Comment by mcepl** [comment] 2022-02-28 09:18
Looking forward for new release with this fix then!

**Closed** 2022-03-01 07:25 UTC
