### ISSUE TITLE
"osc shell" is not concurrent

### ISSUE THREAD

**Issue by pjaitken** [openSUSE/osc#766] opened 2020-03-13 12:49 UTC
While running "osc shell" in one window, subsequent "osc shell" invocations in other windows give:

    ~$ osc shell --root=/var/tmp/osc-buildpackage/build-root/whatever
    mount: /var/tmp/osc-buildpackage/build-root/whatever/proc: none already mounted on /var/tmp/osc-buildpackage/build-root/whatever/proc.
    mount: /var/tmp/osc-buildpackage/build-root/whatever/sys: none already mounted on /var/tmp/osc-buildpackage/build-root/whatever/proc.
    abuild@pentland:~$ 

Upon exiting from this shell, /proc is unmounted from the build root and becomes unavailable in other windows.

Ideally it would detect that /proc is already mounted and neither remount nor dismount it.

**Comment by dmach** [comment] 2023-02-22 09:57
I can't reproduce it, maybe it was fixed in the meantime.
Please open a new issue if the problem persists.

**Closed by dmach** 2023-02-22 09:57 UTC

**Comment by pjaitken** [comment] 2023-02-24 21:38
Each "osc shell" now has its own mount, so the issue nolonger occurs. eg:
```
none on /var/tmp/osc-buildpackage/build-root/whatever/proc type proc (rw,relatime)
none on /var/tmp/osc-buildpackage/build-root/whatever/proc type proc (rw,relatime)
```

The "none already mounted" message still appears, but seems harmless.
