### ISSUE TITLE
`osc-wrapper.py` fails with git tag error

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/osc#1076] opened 2022-07-24 12:00 UTC
Unable to run dev version of `osc`.

UPDATED: See https://github.com/openSUSE/osc/issues/1076#issuecomment-1194482100 for reproducible use case.

```
$ git clone https://github.com/abitrolly/osc
$ cd osc
$ ./osc-wrapper.py
Traceback (most recent call last):
  File "/tmp/osh/osc/./osc-wrapper.py", line 10, in <module>
    from osc import commandline, babysitter
  File "/tmp/osh/osc/osc/commandline.py", line 28, in <module>
    from .core import *
  File "/tmp/osh/osc/osc/core.py", line 10, in <module>
    __version__ = git_version.get_version('0.180.0')
  File "/tmp/osh/osc/osc/util/git_version.py", line 74, in get_version
    raise ValueError(msg)
ValueError: Git tag '0.171.0' doesn't correspond with version '0.180.0' specified in the source code
```

**Versions**
- Operating system: `Fedora Linux 36 (Workstation Edition)`
- Packages: `osc-0.180.0-332.4.1.fc36.noarch`

**Expected behavior**
No errors. Help displayed.

**Comment by abitrolly** [comment] 2022-07-24 12:03
The problem is that GitHub doesn't update tags when refreshing forks, and I don't have the expected tag here https://github.com/abitrolly/osc/tags

That's so weird.

**Comment by abitrolly** [comment] 2022-07-24 12:07
Pushed tags to unbroke this from local clone. Not sure there is a better solution.

**Comment by Thaodan** [comment] 2022-07-25 02:04
Also affects the tarball.

**Comment by Thaodan** [comment] 2022-07-25 02:23
It seams that the git archive filter wasn't executed while the tarball was created resulting in errors when the package is built unless fixed by hand.

**Comment by dmach** [comment] 2022-07-25 11:14
@abitrolly to be honest, I'm unable to reproduce it.
Can you provide more details, preferably in a clean, reproducible environment such as a container?

This is what I tried:
```
$ podman run --rm -it fedora:36
$ dnf install git
$ git clone https://github.com/openSUSE/osc
$ cd osc
$ ./osc-wrapper.py
# osc works, help appears as expected
```

I also tried rebasing my fork to upstream:
```
$ git clone git@github.com:dmach/osc.git osc-dmach
$ cd osc-dmach
$ git tag
# 0.180.0 is NOT in the list
$ git remote add upstream https://github.com/openSUSE/osc.git
$ git fetch upstream
$ git rebase upstream/master
$ ./osc-wrapper.py
# osc works, help appears as expected
```

**Comment by abitrolly** [comment] 2022-07-25 14:22
@dmach

```
✗ git tag -d 0.180.0
Deleted tag '0.180.0' (was 515db3de)                                                                                                                                 /0.0s
➜  osc git:(relconf) ✗ ./osc-wrapper.py  
Traceback (most recent call last):
  File "/tmp/osh/osc/./osc-wrapper.py", line 10, in <module>
    from osc import commandline, babysitter
  File "/tmp/osh/osc/osc/commandline.py", line 28, in <module>
    from .core import *
  File "/tmp/osh/osc/osc/core.py", line 10, in <module>
    __version__ = git_version.get_version('0.180.0')
  File "/tmp/osh/osc/osc/util/git_version.py", line 74, in get_version
    raise ValueError(msg)
ValueError: Git tag '0.179.0' doesn't correspond with version '0.180.0' specified in the source code     
```

**Comment by dmach** [comment] 2022-07-25 14:56
@abitrolly ok, but that's not I wanted. You simply shot yourself in a leg by removing the tag.
I need to know when the current code doesn't work under normal circumstances.

**Comment by abitrolly** [comment] 2022-07-25 18:54
@dmach fork https://github.com/abergmann/osc and then sync it from GitHub button.

![image](https://user-images.githubusercontent.com/8781107/180852748-c461ccb7-bbb0-448c-8a74-668138a53e8a.png)

Tags won't be fetched and you'll end up with the same error.

**Comment by dmach** [comment] 2022-07-26 10:59
The GitHub behavior quite unexpected to me, but yes, it's a valid bug report.
I'll take a look at how I can change the existing behavior to fix this.

**Comment by abitrolly** [comment] 2022-07-26 11:49
Thanks. I updated the issue description to point to the reproducible instructions.

**Comment by dmach** [comment] 2022-08-22 09:42
@abitrolly could you check if patch #1110 fixes the problem for you?

**Comment by abitrolly** [comment] 2022-08-22 16:13
@dmach yes, that fixes it.

**Closed** 2022-08-23 06:27 UTC
Labels: Bug
