### ISSUE TITLE
`osc my sr` crash in sort

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/osc#519] opened 2019-03-01 10:38 UTC
> osc my sr

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 7383, in do_my
    for r in sorted(requests):
TypeError: '<' not supported between instances of 'Request' and 'Request'

> rpm -q osc
osc-0.164.2-lp151.2.1.noarch

**Comment by AdamMajer** [comment] 2019-03-04 12:56
Seems it is still using obsolete __cmp__ instead causing this problem.

https://portingguide.readthedocs.io/en/latest/comparisons.html

**Comment by AdamMajer** [comment] 2019-03-04 13:00
And looks like being worked on as part of https://github.com/openSUSE/osc/pull/492

**Comment by lethliel** [comment] 2019-03-05 13:10
This is caused by the obsolete `__cmp__` function in class Request. 
There are two ways to solve this: 

1. Implement all rich comparison methods in the class
2. change the sorted call to `sorted(requests, key=lambda x: x.reqid)`

I will work on a solution.

**Comment by lethliel** [comment] 2019-03-06 15:25
fixed in commit https://github.com/openSUSE/osc/commit/8851ac7afea810f3507e44c006d5cb8110aa8eee for the python3 branch.

**Closed by lethliel** 2019-03-06 15:25 UTC
