### ISSUE TITLE
python 3 version of osc for debian/ubuntu

### ISSUE THREAD

**Issue by nickbroon** [openSUSE/osc#575] opened 2019-06-05 16:12 UTC
https://build.opensuse.org/package/show/openSUSE:Tools/osc

This produces python 3 packages for recent suse/fedora rpm builds, but the debian/ubuntu version are still python 2. Can the debian.tar.gz packaging there be updated to provide python 3 version for debian/ubuntu?
(As an aside is the debian.tar.gz versioned/stored in git anywhere?)

**Comment by lethliel** [comment] 2019-06-11 10:11
We are currently in discussion to provide a python2 and python3 version for all distributions. So please stay tuned.

**Comment by nickbroon** [comment] 2019-06-11 10:40
@AJDempsey @coldoch

**Comment by nickbroon** [comment] 2019-07-08 10:26
@lethliel Any update from your discussions?

**Comment by lethliel** [comment] 2019-07-09 07:42
This is on my work schedule for the next week

**Comment by jonsger** [comment] 2019-07-25 09:56
Hi,

I just went a head and tried to package osc on Debian with python3. It wasn't that successfull. The result lies in [home:jbrielmaier:branches:openSUSE:Tools](https://build.opensuse.org/project/show/home:jbrielmaier:branches:openSUSE:Tools). It has several caveats:
* it only builds for python3 not for python2. I don't know how to build it properly for both.
* Installation of shell completion files fails. I tried to fix it, but that doesn't work. So they are not installed atm.
* python-m2crypto is not packaged for python3 on debian, so we need to do this in openSUSE:Tools

I'm neither a debian packager nor a user. So feel free to help out, you could submit the packages then to openSUSE:Tools or first to home:jbrielmaier:branches:openSUSE:Tools

**Comment by coldoch** [comment] 2019-08-19 17:06
@jonsger Could we just create two packages in the short term, one for python2 and one for python3?

**Comment by nickbroon** [comment] 2019-09-25 11:00
There is also a ticket raised on Debian about this, as Debian plan to remove Python2 in their next release: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=937218

**Comment by lethliel** [comment] 2019-09-25 11:52
> @jonsger Could we just create two packages in the short term, one for python2 and one for python3?

No. Because at the moment it is not possible to create a osc python3 package for Ubuntu/Debian as the m2crypto version in Ubuntu/Debian is still python2

**Comment by jonsger** [comment] 2019-09-25 11:54
@lethliel According to https://packages.debian.org/search?searchon=names&keywords=m2crypto there is a python3-m2crypto package for bullseye (testing) and sid (unstable)

**Comment by nickbroon** [comment] 2019-10-07 14:08
osc is 'unresolvable' on the xUbuntu_Next  target (which will become Ubuntu 19.10 next week) due to this issue, as Ubuntu has remove Python2 from their distribution.
Within the next few months this will also become an issue with Debian_Testing (which will become Debian 11) as they are also about to remove Python2 from their distribution.
https://build.opensuse.org/package/show/openSUSE:Tools/osc

**Comment by lethliel** [comment] 2019-10-10 09:38
> osc is 'unresolvable' on the xUbuntu_Next target (which will become Ubuntu 19.10 next week) due to this issue, as Ubuntu has remove Python2 from their distribution.
> Within the next few months this will also become an issue with Debian_Testing (which will become Debian 11) as they are also about to remove Python2 from their distribution.
> https://build.opensuse.org/package/show/openSUSE:Tools/osc

Sorry for the delay on this. I was out of commission for two weeks due to an eye operation. 
I will work on this starting next week. 

I already have an working package but it needs some fine tuning. 

@jonsger You are right.

**Comment by lethliel** [comment] 2019-10-25 11:48
Ok. I have now a working osc python3 version for Debian/Ubuntu in
https://build.opensuse.org/package/show/home:mstrigl/osc

The problem is that this works now only python3 which is a problem for
older codestreams because there is no python3-m2crypto now.

**Comment by lethliel** [comment] 2019-10-25 12:16
I now have a control file which builds both versions named osc-py2 and osc-py3.

So which is the way we want to go?

1. Stating old Ubuntu/Debian as unsupported because they do not provide proper dependencies for the python3 osc version
2. Go with the above solution and provide both versions and the user needs to decide which one he takes

Is there an option to tell the control / rules file to build python2 if a specific version of ubuntu/debian is used? 

@marcus-h, @adrianschroeter : opinions welcome

**Comment by nickbroon** [comment] 2019-10-25 12:26
I'm also fine with only building a python3 version for debian. The version of debian that would not be support are incredibly old.

**Comment by nickbroon** [comment] 2019-10-25 12:28
> Is there an option to tell the control / rules file to build python2 if a specific version of ubuntu/debian is used?

Unfortunately debian packaging does not have the equivalent of `%bcond_without` as used in the rpm spec files.

**Comment by nickbroon** [comment] 2019-10-25 12:42
To make seeing the difference to the packaging (both the debian.tar and the osc.spec file) it would be great to see these moved to the osc git repo, and have the_service file extract.
Similar to how build does it https://build.opensuse.org/package/view_file/openSUSE:Tools/build/_service?expand=1

**Comment by nickbroon** [comment] 2020-01-09 20:25
Can someone look at https://build.opensuse.org/request/show/752964 ?

If that's accepted, I'll follow it up with and SR that changes the debian packaging files to use python 3 instead of python 2.

**Comment by nickbroon** [comment] 2020-01-30 15:01
https://build.opensuse.org/request/show/752964 has now been updated to include packaging osc for python3 in debian/ubuntu.
@marcus-h @lethliel @adrianschroeter are you happy to accept the SR?

**Comment by lethliel** [comment] 2020-02-07 10:17
@nickbroon I accepted the SR. Can you please test the resulting packages on debian/ubuntu and report back? 

Then we can close this issue...

**Comment by nickbroon** [comment] 2020-02-07 10:30
Ah, that SR was just for revision 1 or branch, which just unfolds the tarball. I meant to submit revision 2, which also contains the python3 rework. I'll open a new SR with that.

**Comment by nickbroon** [comment] 2020-02-07 11:11
https://build.opensuse.org/request/show/771059 opened with the actual python3 packaging for debian changes.

**Comment by nickbroon** [comment] 2020-02-07 13:41
Hopefully last one for a https://build.opensuse.org/request/show/771917
Thanks for merging the previous one, its great to finally have osc available as python3 for recent debian/ubuntu releases.

**Comment by lethliel** [comment] 2020-02-07 13:47
Ubuntu Next is unresolvable:

`nothing provides dh-python, nothing provides dh-python needed by python3-all`

**Comment by nickbroon** [comment] 2020-02-07 13:47
With https://build.opensuse.org/request/show/771917 merged, I've tested the packages on Ubuntu 19.10 and Debian 10 and all seems to work well.

**Comment by nickbroon** [comment] 2020-02-07 13:49
I'll investigate the Ubuntu next issue. I think it's been broken for a while as they go through their python2 deprecation.

**Comment by lethliel** [comment] 2020-02-07 13:50
Ok Thanks :-)

**Comment by nickbroon** [comment] 2020-02-07 14:10
'focal' is ubuntu next, and it appears both packages are available.
https://packages.ubuntu.com/focal/python3-all
https://packages.ubuntu.com/focal/dh-python
I'll need to poke a little further.
Is possible to see what packages the https://build.opensuse.org/project/show/Ubuntu:Next OBS projects contains?

**Comment by nickbroon** [comment] 2020-02-07 15:10
https://build.opensuse.org/project/monitor/openSUSE:Tools?utf8=%E2%9C%93&defaults=0&succeeded=1&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&arch_i586=1&arch_x86_64=1&repo_Debian_10=1&repo_Debian_Testing=1&repo_Debian_Unstable=1&repo_xUbuntu_18_04=1&repo_xUbuntu_19_10=1&repo_xUbuntu_Next=1

Looking at Ubuntu:Next overall, it appears in quite a bad state. Very little is building against it. Is the OBS Ubuntu:Next mirror project is incomplete and/or missing some prjconf?

**Comment by nickbroon** [comment] 2020-02-11 10:38
@lethliel https://build.opensuse.org/request/show/772679 another update to help support install on older debian/ubuntu releases.

**Comment by rtamalin** [comment] 2020-02-11 20:48
> @lethliel [build.opensuse.org/request/show/772679](https://build.opensuse.org/request/show/772679) another update to help support install on older debian/ubuntu releases.

As per my comments on the submit request that change doesn't appear to be enough as the changes in revision 318 (https://build.opensuse.org/request/show/771059) switched to installing a Python3 based osc command, but there isn't a python3-m2crypto package available for Ubuntu versions before 19.10 (Eoan) per https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=python3-m2crypto

**Comment by nickbroon** [comment] 2020-02-11 22:58
I tested that build.opensuse.org/request/show/772679 which makes python3-m2crypto using a recommend allows osc to be installed on ubuntu 18.04. See below (same would apply to ubuntu 16.04 and also debian 9).
There is no python3-m2crypto for ubuntu 18.04 but it's not strictly necessary so the optional recommend is sufficient. (It might require using 'sslcertck = 0' in .oscrc depending on config)

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
# cat /etc/apt/sources.list.d/osc.list
deb [trusted=yes] https://download.opensuse.org/repositories/home:/nickbrown:/osc_debian_files/xUbuntu_18.04/ ./
# apt-cache policy osc
osc:
  Installed: (none)
  Candidate: 0.167.2
  Version table:
     0.167.2 500
        500 https://download.opensuse.org/repositories/home:/nickbrown:/osc_debian_files/xUbuntu_18.04 ./ Packages
     0.162.1-1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
# apt install osc
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  bash-completion dbus debootstrap debugedit dirmngr file gir1.2-glib-2.0 gnupg gnupg-l10n gnupg-utils gpg gpg-agent
  gpg-wks-client gpg-wks-server gpgconf gpgsm libapparmor1 libarchive-tools libarchive13 libasn1-8-heimdal libassuan0
  libbytes-random-secure-perl libcap2 libcrypt-random-seed-perl libcrypt-ssleay-perl libdbus-1-3 libdw1 libelf1
  libexpat1 libgdbm-compat4 libgdbm5 libgirepository-1.0-1 libglib2.0-0 libglib2.0-data libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libicu60 libkrb5-26-heimdal
  libksba8 libldap-2.4-2 libldap-common liblua5.2-0 liblzo2-2 libmagic-mgc libmagic1 libmath-random-isaac-perl
  libmath-random-isaac-xs-perl libmpdec2 libnpth0 libnspr4 libnss3 libperl5.26 libpopt0 libpsl5 libpython3-stdlib
  libpython3.6-minimal libpython3.6-stdlib libreadline7 libroken18-heimdal librpm8 librpmbuild8 librpmio8 librpmsign8
  libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libwind0-heimdal libxml2 mime-support multiarch-support
  netbase obs-build perl perl-modules-5.26 perl-openssl-defaults pinentry-curses publicsuffix python3
  python3-asn1crypto python3-cffi-backend python3-crypto python3-cryptography python3-dbus python3-gi python3-idna
  python3-keyring python3-keyrings.alt python3-minimal python3-progressbar python3-rpm python3-secretstorage
  python3-six python3.6 python3.6-minimal readline-common rpm rpm-common rpm2cpio shared-mime-info sudo wget
  xdg-user-dirs xz-utils
Suggested packages:
  default-dbus-session-bus | dbus-session-bus ubuntu-archive-keyring rpm-i18n dbus-user-session libpam-systemd
  pinentry-gnome3 tor parcimonie xloadimage scdaemon lrzip gdbm-l10n libsasl2-modules-gssapi-mit
  | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql perl-doc
  libterm-readline-gnu-perl | libterm-readline-perl-perl make pinentry-doc python3-doc python3-tk python3-venv
  python-crypto-doc python-cryptography-doc python3-cryptography-vectors python-dbus-doc python3-dbus-dbg
  gnome-keyring libkf5wallet-bin gir1.2-gnomekeyring-1.0 python-secretstorage-doc python3.6-venv python3.6-doc
  binutils binfmt-support readline-doc alien python elfutils rpmlint rpm2html
Recommended packages:
  python3-m2crypto
The following NEW packages will be installed:
  bash-completion dbus debootstrap debugedit dirmngr file gir1.2-glib-2.0 gnupg gnupg-l10n gnupg-utils gpg gpg-agent
  gpg-wks-client gpg-wks-server gpgconf gpgsm libapparmor1 libarchive-tools libarchive13 libasn1-8-heimdal libassuan0
  libbytes-random-secure-perl libcap2 libcrypt-random-seed-perl libcrypt-ssleay-perl libdbus-1-3 libdw1 libelf1
  libexpat1 libgdbm-compat4 libgdbm5 libgirepository-1.0-1 libglib2.0-0 libglib2.0-data libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libicu60 libkrb5-26-heimdal
  libksba8 libldap-2.4-2 libldap-common liblua5.2-0 liblzo2-2 libmagic-mgc libmagic1 libmath-random-isaac-perl
  libmath-random-isaac-xs-perl libmpdec2 libnpth0 libnspr4 libnss3 libperl5.26 libpopt0 libpsl5 libpython3-stdlib
  libpython3.6-minimal libpython3.6-stdlib libreadline7 libroken18-heimdal librpm8 librpmbuild8 librpmio8 librpmsign8
  libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libwind0-heimdal libxml2 mime-support multiarch-support
  netbase obs-build osc perl perl-modules-5.26 perl-openssl-defaults pinentry-curses publicsuffix python3
  python3-asn1crypto python3-cffi-backend python3-crypto python3-cryptography python3-dbus python3-gi python3-idna
  python3-keyring python3-keyrings.alt python3-minimal python3-progressbar python3-rpm python3-secretstorage
  python3-six python3.6 python3.6-minimal readline-common rpm rpm-common rpm2cpio shared-mime-info sudo wget
  xdg-user-dirs xz-utils
0 upgraded, 108 newly installed, 0 to remove and 18 not upgraded.
Need to get 31.2 MB of archives.
After this operation, 147 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by rtamalin** [comment] 2020-03-04 16:31
Just tested with the latest release of osc (0.168.0) for Ubuntu systems...

However while the osc package successfully installs on Ubuntu 18.04/Bionic LTS, what is installed ends up being useless:

```ubuntu@ubuntu:~$ lsb_release -d
Description:	Ubuntu 18.04.4 LTS
ubuntu@ubuntu:~$ osc --version
0.168.0
ubuntu@ubuntu:~$ osc ls
No module named 'M2Crypto'
M2Crypto is needed to access https://api.opensuse.org in a secure way.
Please install python-m2crypto.
```
However since there is NO python3-m2crypto package currently available for Bionic - or any Ubuntu release prior to Ubuntu 19.10/Eoan, as per https://packages.ubuntu.com/search?keywords=python3-m2crypto&searchon=names&suite=all&section=all there is no way to install a Python3 version of the M2Crypto module to satisfy this requirement to get a functional Python3 based version of osc to run on active Ubuntu LTS releases.

As such you are not actually building a viable osc package for Ubuntu LTS releases, until the Ubuntu 20.04/Focal LTS release happens next month...

And the only non-LTS release you actually support is Ubuntu 19.10/Eoan...

**Comment by rtamalin** [comment] 2020-03-04 16:36
Just tested with the latest release of osc (0.168.0) for Ubuntu systems...

However while the osc package successfully installs on Ubuntu 18.04/Bionic LTS, what is installed ends up being useless:

`ubuntu@ubuntu:~$ lsb_release -d`
`Description:	Ubuntu 18.04.4 LTS`
`ubuntu@ubuntu:~$ osc --version`
`0.168.0`
`ubuntu@ubuntu:~$ osc ls`
`No module named 'M2Crypto'`
`M2Crypto is needed to access https://api.opensuse.org in a secure way.`
`Please install python-m2crypto.`

However since there is NO python3-m2crypto package currently available for Bionic - or any Ubuntu release prior to Ubuntu 19.10/Eoan, as per https://packages.ubuntu.com/search?keywords=python3-m2crypto&searchon=names&suite=all&section=all there is no way to install a Python3 version of the M2Crypto module to satisfy this requirement to get a functional Python3 based version of osc to run on active Ubuntu LTS releases.

As such you are not actually building a viable osc package for Ubuntu LTS releases, until the Ubuntu 20.04/Focal LTS release happens next month...

And the only non-LTS release you actually support is Ubuntu 19.10/Eoan...

**Comment by nickbroon** [comment] 2020-03-04 17:51
The lack of python3-m2crypto on recent debian/unbuntu releases is less than ideal, hopefully they'll backport it soon.
But osc can be made functional, though less secure, by add `sslcertck = 0` to your .oscrc file

~/.oscrc
```
[https://api.opensuse.org]
sslcertck = 0
username=
pass=
```

**Comment by lethliel** [comment] 2020-03-05 10:12
I already opened a backport request for Bionic: https://bugs.launchpad.net/bionic-backports/+bug/1863863

**Closed** 2020-03-13 10:22 UTC
