### ISSUE TITLE
osc --verbose --debug shows only a subset of the remote communication

### ISSUE THREAD

**Issue by olafhering** [openSUSE/osc#1498] opened 2024-02-26 07:47 UTC
We have that one single host in the lab for which `api.suse.de` always returns `401` (`SD-148214`).
The very same $HOME works from other hosts in the lab.
The output of `rpm -qa` on non-working vs. working host shows no obvious differences to explain the 401 error.

It is difficult to debug this failure, because `osc --verbose --debug <cmd> <prj>` shows only a subset of the communication with the remote side. Like it shows only the `GET` request. I'm sure there is much more going on prior the HTTP request.

Please let `osc --debug --verbose` show the entire conversation, so that it will be easy to compare a working vs. a non-working host.

**Comment by dmach** [comment] 2024-02-26 08:35
The `--verbose` and `--debug` options control overall verbosity of osc, but that doesn't include http traffic.
You need to use `-H / --http-debug` instead.

**Comment by olafhering** [comment] 2024-02-26 08:47
Well, that just shows a different `signature=<unleserlich>` in the second attempt. Not how osc came to the conclusion that such `signature=` would be valid.

But yeah, in the end `--http-full-debug` shows more. Unfortunately, nothing helpful for the case at hand.

**Comment by dmach** [comment] 2024-02-26 12:12
`--http-full-debug` and `--http-debug` are nearly identical, the only difference is removed auth and cookie headers from the reqeust.

**Comment by dmach** [comment] 2024-02-28 07:34
> We have that one single host in the lab for which `api.suse.de` always returns `401` (`SD-148214`).

We have fixed the issue - the root cause was system time off by several minutes which impacted ssh auth.

> Please let `osc --debug --verbose` show the entire conversation, so that it will be easy to compare a working vs. a non-working host.

We have clarified that there are  `--http-full-debug` and `--http-debug` options for that.

I don't think there's any change in osc needed. Closing.

**Closed by dmach** 2024-02-28 07:34 UTC
Labels: Bug
