### ISSUE TITLE
Declined request erroneously shows up in "osc rq list" of target project

### ISSUE THREAD

**Issue by peti** [openSUSE/osc#323] opened 2017-08-22 11:01 UTC
The command 

    osc rq list devel:languages:haskell git-annex

returns (among other things) the request https://build.opensuse.org/request/show/482996, even though it's been declined several months ago and therefore no longer relevant for the `devel:languages:haskell` project. According to @adrianschroeter, this is a bug in `osc` and I was asked to report it here.

**Comment by lethliel** [comment] 2017-08-22 11:13
I talked with Adrian. Basically this works as intended. Requests with state 'new', 'declined' and 'review' are listed. 

So declined requests whose target project is the one to be listed --> skip

**Comment by peti** [comment] 2017-08-22 11:20
OK. In that case, can someone please revoke/close that request so that it *stops* showing up in that list? That SR has been dead for months, but the originator won't revoke it for whatever reason.

**Comment by lethliel** [comment] 2017-08-22 11:24
I am investigating a opportunity to filter declined requests based on the target porject.
So that they will still show up if you list requests in the source project. (This might be important for the requester to see the declined ones also.) 

But I agree: On the target project it is not relevant.

**Comment by dmach** [comment] 2023-02-22 13:06
I believe osc works as intended.
All the following states indicate requests that require an action (either review or resubmit): new, review, declined
I wouldn't say that declined requests are not relevant on the target project. It probably depends on the use case and who runs the query.

I don't think we should change this behavior. Closing.

**Closed by dmach** 2023-02-22 13:06 UTC
